//hACER UN CPONTADOR DE PULSOS, CADA VEZ QUE PRESIONAMOS EL PULSADOR LAS TIENE QUE
//PARPADEAR EL LED(CON I++;),CREAMOS OTRA VARIABLE CONTADOR Y LA HACIAMOS CONTARE
//HACER QUE HACER UN RESET DEL CONTADOR, CUANDO QUIERO LOQ UE QUIERA QUE HAGA EL CONTADOR VUELVE  A 0
//ESO MEZCLADO CON UN BUCLE FOR LA CANTIDAD DE VECES
//TRAER SERVOMOTOR O LDR

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
