/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui;
import javax.swing.JOptionPane;
import mypackage.connector.Connector;
import mypackage.entities.persistence.Curso;
import mypackage.enums.Dia;
import mypackage.enums.Turno;
import mypackage.repositories.interfaces.I_AlumnoRepository;
import mypackage.repositories.interfaces.I_CursoRepository;
import mypackage.repositories.jdbc.AlumnoRepository;
import mypackage.repositories.jdbc.CursoRepository;
import mypackage.utils.swing.Table;
import mypackage.utils.swing.Validator;


/**
 *
 * @author andre
 */
public class FormCursos extends javax.swing.JInternalFrame {

    private I_CursoRepository cursoRepository = new CursoRepository(Connector.getConnection());
    private I_AlumnoRepository alumnoRepository = new AlumnoRepository(Connector.getConnection());
 
    
    public FormCursos() {
        super(
                "Formulario Cursos",
                false,
                true,
                false,
                true
        );
        initComponents();
        
     

        CargarElementosPrivados();
    }

    private void CargarElementosPrivados() {
        //Cargamos los elementos de los comboboxs
        //Cargar dia
        jComboBoxDia.removeAllItems();
        for (Dia d : Dia.values()) {
            jComboBoxDia.addItem(d);
        }

        //cargar Turno
        jComboBoxTurno.removeAllItems();
        for (Turno t : Turno.values()) {
            jComboBoxTurno.addItem(t);
        }
        //Cargar tabla cursos
        new Table().cargar(jTableCursos, cursoRepository.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        button1 = new java.awt.Button();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelProfesor = new javax.swing.JLabel();
        jTextFieldProfesor = new javax.swing.JTextField();
        jLabelDia = new javax.swing.JLabel();
        jLabelTurno = new javax.swing.JLabel();
        jLabelOutput = new javax.swing.JLabel();
        jButtonAgregarCurso = new javax.swing.JButton();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jComboBoxTurno = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCursos = new javax.swing.JTable();
        jLabelBuscarTitulo = new javax.swing.JLabel();
        jTextFieldBuscarTitulo = new javax.swing.JTextField();
        jButtonElimiinar = new javax.swing.JButton();
        jButtonMostrarAlumnos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        button1.setLabel("button1");

        setAlignmentX(50.0F);
        setAlignmentY(50.0F);

        jLabelTitulo.setText("Titulo:");

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jLabelProfesor.setText("Profesor");

        jLabelDia.setText("Dia:");

        jLabelTurno.setText("Turno:");

        jLabelOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonAgregarCurso.setText("Agregar Curso");
        jButtonAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCursoActionPerformed(evt);
            }
        });

        jTableCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableCursos);

        jLabelBuscarTitulo.setText("Buscar titulo:");

        jTextFieldBuscarTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarTituloKeyReleased(evt);
            }
        });

        jButtonElimiinar.setText("Eliminar");
        jButtonElimiinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElimiinarActionPerformed(evt);
            }
        });

        jButtonMostrarAlumnos.setText("Mostrar Alumnos");
        jButtonMostrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelProfesor)
                                    .addComponent(jLabelDia)
                                    .addComponent(jLabelTurno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                            .addComponent(jTextFieldProfesor))
                                        .addComponent(jComboBoxDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxTurno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelBuscarTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonElimiinar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonMostrarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProfesor)
                    .addComponent(jTextFieldProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTurno)
                    .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButtonAgregarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonElimiinar)
                    .addComponent(jLabelBuscarTitulo))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMostrarAlumnos)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jButtonAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCursoActionPerformed

        if (!validar()) {
            return;
        }
        
        Curso curso=new Curso(
                jTextFieldTitulo.getText(),
                jTextFieldProfesor.getText(),
                jComboBoxDia.getItemAt(jComboBoxDia.getSelectedIndex()),//Nos devuelve un objeto del tipo dia segun el indice seleccionado
                jComboBoxTurno.getItemAt(jComboBoxTurno.getSelectedIndex())
        );
        //Guardamos
        cursoRepository.save(curso);
        //Lo mostramos en el input de la gui
        jLabelOutput.setText("Se dio de alta el curso con el id:"+curso.getId());
        //Limpiamos la salida de textField
        limpiar();   
        CargarElementosPrivados();
    }
    
    private void limpiar(){
        jTextFieldTitulo.setText("");
         jTextFieldTitulo.requestFocus();
        jTextFieldProfesor.setText("");
        jComboBoxDia.setSelectedIndex(0);
        jComboBoxTurno.setSelectedIndex(0);
        
        
    }
    private boolean validar() {
        
        if (!new Validator(jTextFieldTitulo).length(3, 10)) {
            return false;
        }
        if (!new Validator(jTextFieldProfesor).length(3, 10)) {
            return false;
        }
        return true;
    
    }//GEN-LAST:event_jButtonAgregarCursoActionPerformed

    private void jTextFieldBuscarTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarTituloKeyReleased
        new Table().cargar(jTableCursos, cursoRepository.getLikeTitulo(jTextFieldBuscarTitulo.getText()));
    }//GEN-LAST:event_jTextFieldBuscarTituloKeyReleased

    private void jButtonElimiinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElimiinarActionPerformed
        int row=jTableCursos.getSelectedRow();
        if(row == -1){
            return;
        }
        //Se pide la fila con el id que queremos eliminar y con el cero se elimina
        int id=(int)jTableCursos.getValueAt(row,0);
        //System.out.println("Id eliminado:"+id);
        if(JOptionPane.showConfirmDialog(this, "Se borrara el curso con el id "+id+"!!")!=0){
            return;
        }
        Curso objetoCurso=cursoRepository.getById(id);
        //Pedimos una lista de alumnos 
        if(alumnoRepository.getByCurso(objetoCurso).size()!=0){
            JOptionPane.showMessageDialog(this,"El curso no se puede eliminar porque contiene alumnos!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        //Borramos de la lista el elemento con el id pasadoe n el buscador
        cursoRepository.remove(objetoCurso);
        //Cargamos los elementos nuevamente
          CargarElementosPrivados();
        
    }//GEN-LAST:event_jButtonElimiinarActionPerformed

    private void jButtonMostrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarAlumnosActionPerformed
        int row=jTableCursos.getSelectedRow();
        if(row == -1){
            return;
        }
        //Se pide la fila con el id que queremos eliminar y con el cero se elimina
        int id=(int)jTableCursos.getValueAt(row,0);
        
        Curso objetoCurso=cursoRepository.getById(id);
        
        //Listo los alumnos
        ListarAlumnos listarAlumnos=new ListarAlumnos(objetoCurso);
        //Obtengo el desktop padre
        this.getParent().add(listarAlumnos);
        //Lo hacemos visible
        listarAlumnos.setVisible(true);
    }//GEN-LAST:event_jButtonMostrarAlumnosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jButtonAgregarCurso;
    private javax.swing.JButton jButtonElimiinar;
    private javax.swing.JButton jButtonMostrarAlumnos;
    private javax.swing.JComboBox<Dia> jComboBoxDia;
    private javax.swing.JComboBox<Turno> jComboBoxTurno;
    private javax.swing.JLabel jLabelBuscarTitulo;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelOutput;
    private javax.swing.JLabel jLabelProfesor;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableCursos;
    private javax.swing.JTextField jTextFieldBuscarTitulo;
    private javax.swing.JTextField jTextFieldProfesor;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

}